providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps || npm install --legacy-peer-deps"]

[phases.build]
cmds = ["NITRO_PRESET=node_server npm run build"]

[start]
cmd = "npm start"
