/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MeningRouteImport } from './routes/mening'
import { Route as QoidalarRouteImport } from './routes/qoidalar'
import { Route as SotishRouteImport } from './routes/sotish'
import { Route as AkkauntIdRouteImport } from './routes/akkaunt.$id'
import { Route as ApiPublicDiagRouteImport } from './routes/api/public/diag'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicTgLoginRouteImport } from './routes/api/public/tg-login'
import { Route as ApiPublicTelegramSetupRouteImport } from './routes/api/public/telegram/setup'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MeningRoute = MeningRouteImport.update({
  id: '/mening',
  path: '/mening',
  getParentRoute: () => rootRouteImport,
} as any)
const QoidalarRoute = QoidalarRouteImport.update({
  id: '/qoidalar',
  path: '/qoidalar',
  getParentRoute: () => rootRouteImport,
} as any)
const SotishRoute = SotishRouteImport.update({
  id: '/sotish',
  path: '/sotish',
  getParentRoute: () => rootRouteImport,
} as any)
const AkkauntIdRoute = AkkauntIdRouteImport.update({
  id: '/akkaunt/$id',
  path: '/akkaunt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiagRoute = ApiPublicDiagRouteImport.update({
  id: '/api/public/diag',
  path: '/api/public/diag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTgLoginRoute = ApiPublicTgLoginRouteImport.update({
  id: '/api/public/tg-login',
  path: '/api/public/tg-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramSetupRoute = ApiPublicTelegramSetupRouteImport.update({
  id: '/api/public/telegram/setup',
  path: '/api/public/telegram/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/mening': typeof MeningRoute
  '/qoidalar': typeof QoidalarRoute
  '/sotish': typeof SotishRoute
  '/akkaunt/$id': typeof AkkauntIdRoute
  '/api/public/diag': typeof ApiPublicDiagRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/tg-login': typeof ApiPublicTgLoginRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/mening': typeof MeningRoute
  '/qoidalar': typeof QoidalarRoute
  '/sotish': typeof SotishRoute
  '/akkaunt/$id': typeof AkkauntIdRoute
  '/api/public/diag': typeof ApiPublicDiagRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/tg-login': typeof ApiPublicTgLoginRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/mening': typeof MeningRoute
  '/qoidalar': typeof QoidalarRoute
  '/sotish': typeof SotishRoute
  '/akkaunt/$id': typeof AkkauntIdRoute
  '/api/public/diag': typeof ApiPublicDiagRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/tg-login': typeof ApiPublicTgLoginRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/mening'
    | '/qoidalar'
    | '/sotish'
    | '/akkaunt/$id'
    | '/api/public/diag'
    | '/api/public/health'
    | '/api/public/tg-login'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/mening'
    | '/qoidalar'
    | '/sotish'
    | '/akkaunt/$id'
    | '/api/public/diag'
    | '/api/public/health'
    | '/api/public/tg-login'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/mening'
    | '/qoidalar'
    | '/sotish'
    | '/akkaunt/$id'
    | '/api/public/diag'
    | '/api/public/health'
    | '/api/public/tg-login'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  MeningRoute: typeof MeningRoute
  QoidalarRoute: typeof QoidalarRoute
  SotishRoute: typeof SotishRoute
  AkkauntIdRoute: typeof AkkauntIdRoute
  ApiPublicDiagRoute: typeof ApiPublicDiagRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicTgLoginRoute: typeof ApiPublicTgLoginRoute
  ApiPublicTelegramSetupRoute: typeof ApiPublicTelegramSetupRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mening': {
      id: '/mening'
      path: '/mening'
      fullPath: '/mening'
      preLoaderRoute: typeof MeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qoidalar': {
      id: '/qoidalar'
      path: '/qoidalar'
      fullPath: '/qoidalar'
      preLoaderRoute: typeof QoidalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sotish': {
      id: '/sotish'
      path: '/sotish'
      fullPath: '/sotish'
      preLoaderRoute: typeof SotishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akkaunt/$id': {
      id: '/akkaunt/$id'
      path: '/akkaunt/$id'
      fullPath: '/akkaunt/$id'
      preLoaderRoute: typeof AkkauntIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diag': {
      id: '/api/public/diag'
      path: '/api/public/diag'
      fullPath: '/api/public/diag'
      preLoaderRoute: typeof ApiPublicDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tg-login': {
      id: '/api/public/tg-login'
      path: '/api/public/tg-login'
      fullPath: '/api/public/tg-login'
      preLoaderRoute: typeof ApiPublicTgLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/setup': {
      id: '/api/public/telegram/setup'
      path: '/api/public/telegram/setup'
      fullPath: '/api/public/telegram/setup'
      preLoaderRoute: typeof ApiPublicTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  MeningRoute: MeningRoute,
  QoidalarRoute: QoidalarRoute,
  SotishRoute: SotishRoute,
  AkkauntIdRoute: AkkauntIdRoute,
  ApiPublicDiagRoute: ApiPublicDiagRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicTgLoginRoute: ApiPublicTgLoginRoute,
  ApiPublicTelegramSetupRoute: ApiPublicTelegramSetupRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
