CREATE TABLE public.bot_updates (
  update_id bigint PRIMARY KEY,
  received_at timestamptz NOT NULL DEFAULT now()
);
GRANT ALL ON public.bot_updates TO service_role;
ALTER TABLE public.bot_updates ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.bot_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level text NOT NULL CHECK (level IN ('info', 'warn', 'error')),
  event text NOT NULL,
  message text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT ALL ON public.bot_logs TO service_role;
ALTER TABLE public.bot_logs ENABLE ROW LEVEL SECURITY;
CREATE INDEX bot_logs_created_at_idx ON public.bot_logs (created_at DESC);

INSERT INTO public.app_settings (key, value) VALUES
  ('bot_force_sub', 'on'),
  ('bot_channel', 'https://t.me/PUBG_SAVDO_CHANNEL'),
  ('bot_support', '@PUBG_SAVDO_ORG_ADMIN'),
  ('bot_reviews', 'https://t.me/PUBG_SAVDO_CHANNEL')
ON CONFLICT (key) DO NOTHING;